name: Static Code Checks
description: Run linting, type checking and unused-code analysis
runs:
  using: composite
  steps:
    - run: npm run lint
      shell: bash
    - run: npm run check:types
      shell: bash
    - run: npm run check:unused
      shell: bash
