name: Setup Node.js and dependencies
description: Setup Node.js and install dependencies

inputs:
  token:
    description: GitHub Personal Access Token for private package access
    required: true

runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version-file: .nvmrc
        cache: npm

    - name: Setup .npmrc from template
      run: |
        sed "s/@@GITHUB_PAT@@/${{ inputs.token }}/g" .npmrc.template > .npmrc
        cat .npmrc
      shell: bash

    - name: Install dependencies
      run: npm ci
      shell: bash
