name: Quality Assurance & End-to-End Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  quality-assurance:
    name: Quality Assurance
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js + npm cache
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: npm
          cache-dependency-path: package-lock.json

      - name: Setup .npmrc from template
        run: npm run setup-npmrc
        env:
          GITHUB_PAT: ${{ secrets.GH_PAT }}

      - name: Install dependencies
        run: npm ci

      - name: Validate package version vs. release tag
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          PACKAGE_VERSION=$(node -p "require('./package.json').version")
          RELEASE_TAG=${GITHUB_REF#refs/tags/}
          echo "Package version: v$PACKAGE_VERSION"
          echo "Release tag:     $RELEASE_TAG"
          if [ "v$PACKAGE_VERSION" != "$RELEASE_TAG" ]; then
            echo "::error::Package version and git tag differ!"
            exit 1
          fi
          echo "Version validation passed"

      - name: Run linting
        run: npm run lint

      - name: Type check
        run: npm run check:types

      - name: Check for unused code & dependencies
        run: npm run check:unused

      - name: Run unit tests
        run: npm run test

      - name: Build application
        run: npm run build:ci

  end-to-end-tests:
    name: End-to-End Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js + npm cache
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: npm
          cache-dependency-path: package-lock.json

      - name: Setup .npmrc from template
        run: npm run setup-npmrc
        env:
          GITHUB_PAT: ${{ secrets.GH_PAT }}

      - name: Install dependencies
        run: npm ci

      - name: Restore Playwright browser cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('package-lock.json') }}

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Build application for end-to-end tests
        run: npm run build:ci

      - name: Run end-to-end tests
        run: npm run test:e2e

      - name: Upload Playwright report
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
