# Quality assurance & end-to-end tests workflow
#
# This workflow runs comprehensive testing for all commits and PRs, including release commits.
#
# Design decisions:
# 1. **Always test**: Every commit to main branch is tested, including release commits.
#    This ensures that even if admins bypass branch protection, code is always validated.
#
# 2. **Performance improvements**:
#    - Optimized npm flags (--no-audit --no-fund --loglevel=error)
#    - Playwright browser caching
#    - Composite actions for reusable steps
#
# 3. **Modular structure**:
#    - Composite actions for repeatable tasks (setup-npmrc, setup-node-dependencies, setup-playwright, quality-assurance)
#    - Improved maintainability through centralized definition of common steps
#
# 4. **Artifact preservation**: Uploads Playwright reports for debugging failed tests,
#    even when the workflow fails (but not when cancelled).
#
# 5. **Concurrency control**: Prevents parallel runs for the same PR/branch to save
#    CI resources. Main branch pushes run independently as they represent deployment stages.

name: Quality assurance & end-to-end tests

concurrency:
  group: app-qa-e2e-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  quality-assurance:
    name: Quality assurance
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .npmrc for GitHub packages
        uses: ./.github/actions/setup-npmrc
        with:
          github_token: ${{ secrets.GH_PAT }}

      - name: Setup Node and install dependencies
        uses: ./.github/actions/setup-node-dependencies

      - name: Run quality assurance
        uses: ./.github/actions/quality-assurance

      - name: Verify package can be packed
        run: |
          npm pack --dry-run
          echo "Package packing verification passed"

  end-to-end-tests:
    name: End-to-end tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .npmrc for GitHub packages
        uses: ./.github/actions/setup-npmrc
        with:
          github_token: ${{ secrets.GH_PAT }}

      - name: Setup Node and install dependencies
        uses: ./.github/actions/setup-node-dependencies

      - name: Setup Playwright for end-to-end tests
        uses: ./.github/actions/setup-playwright

      - name: Build application for end-to-end tests
        run: npm run build

      - name: Run end-to-end tests
        run: npm run test:e2e

      - name: Upload end-to-end test report
        if: ${{ always() && !cancelled() }}
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
